# Generated by Django 5.1.4 on 2025-01-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İletisim',
                'verbose_name_plural': 'İletisimler',
            },
        ),
    ]
