# Generated by Django 5.1.4 on 2025-01-17 16:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Hakkımızda Başlığı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Hakkımızda Açıklaması')),
                ('image', models.ImageField(upload_to='about', verbose_name='Arkaplan Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'İletişim',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Resim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
        migrations.CreateModel(
            name='GeneralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Genel Bilgiler Başlığı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Adres')),
                ('main_phone_number', models.CharField(max_length=50, verbose_name='En çok kullanılan telefon numarası')),
                ('favicon', models.ImageField(upload_to='favicon', verbose_name='Favicon')),
                ('navbar_img', models.ImageField(upload_to='navbar_img', verbose_name='Navbar Resmi')),
                ('footer_img', models.ImageField(upload_to='footer_img', verbose_name='Footer Resmi')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook linki')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='İnstagram linki')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter linki')),
                ('youtube_1', models.URLField(blank=True, null=True, verbose_name='Youtube birinci linki')),
                ('youtube_2', models.URLField(blank=True, null=True, verbose_name='Youtube ikinci linki')),
                ('youtube_3', models.URLField(blank=True, null=True, verbose_name='Youtube üçüncü linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Genel Bilgiler',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_arabic', ckeditor.fields.RichTextField(verbose_name='Metin (Arapça)')),
                ('text_translation', ckeditor.fields.RichTextField(verbose_name='Metin (Çeviri)')),
                ('source', models.CharField(max_length=200, verbose_name='Kaynak')),
                ('image', models.ImageField(upload_to='home_slider', verbose_name='Resim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Ana Sayfa Sliderları',
            },
        ),
        migrations.CreateModel(
            name='IslamicConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Şartın Başlığı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Şartın Açıklaması')),
                ('icon', models.CharField(max_length=200, verbose_name='Şartın Simgesi (İkon)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'İslamın Şartları',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Görevler Başlığı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='mission', verbose_name='Resim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Görevler',
            },
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Baslığı')),
                ('about_img', models.ImageField(upload_to='about_banner_img', verbose_name='Hakkımızda Banner Resmi')),
                ('about_arabic_text', ckeditor.fields.RichTextField(verbose_name='Hakkımızda Banner Metin (Arapça)')),
                ('article_img', models.ImageField(upload_to='article_banner_img', verbose_name='Makale Banner Resmi')),
                ('article_arabic_text', ckeditor.fields.RichTextField(verbose_name='Makale Banner Metin (Arapça)')),
                ('article_category_img', models.ImageField(upload_to='article_category_banner_img', verbose_name='Makale Detayları Banner Resmi')),
                ('article_category_arabic_text', ckeditor.fields.RichTextField(verbose_name='Makale Kategorisi Banner Metin (Arapça)')),
                ('article_detail_img', models.ImageField(upload_to='article_detail_banner_img', verbose_name='Makale Detayları Banner Resmi')),
                ('article_detail_arabic_text', ckeditor.fields.RichTextField(verbose_name='Makale Detayları Banner Metin (Arapça)')),
                ('lesson_img', models.ImageField(upload_to='lesson_banner_img', verbose_name='Ders Banner Resmi')),
                ('lesson_arabic_text', ckeditor.fields.RichTextField(verbose_name='Ders Banner Metin (Arapça)')),
                ('lesson_detail_img', models.ImageField(upload_to='lesson_detail_banner_img', verbose_name='Ders Detayları Banner Resmi')),
                ('lesson_detail_arabic_text', ckeditor.fields.RichTextField(verbose_name='Ders Detayları Banner Metin (Arapça)')),
                ('galery_img', models.ImageField(upload_to='galery_banner_img', verbose_name='Galeri Banner Resmi')),
                ('galery_arabic_text', ckeditor.fields.RichTextField(verbose_name='Galeri Banner Metin (Arapça)')),
                ('contact_img', models.ImageField(upload_to='contact_banner_img', verbose_name='İletişim Banner Resmi')),
                ('contact_arabic_text', ckeditor.fields.RichTextField(verbose_name='İletişim Banner Metin (Arapça)')),
                ('subcsribe_title', models.CharField(max_length=200, verbose_name='Abone Ol Banner Başlığı')),
                ('subcsribe_img', models.ImageField(upload_to='subscribe_banner_img', verbose_name='Abone Ol Banner Resmi')),
            ],
            options={
                'verbose_name_plural': 'Sayfa Bannerları',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Telefon Numarası Başlığı')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Telefon Numaraları',
            },
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(help_text='İçeriğin kısa açıklaması (SEO ve Sosyal Medya için)', verbose_name='Açıklama')),
                ('keywords', models.CharField(blank=True, help_text='SEO için anahtar kelimeleri virgülle ayırarak girin.', max_length=300, verbose_name='Anahtar Kelimeler')),
                ('image', models.ImageField(blank=True, help_text='Sosyal medyada gösterilecek görsel.', null=True, upload_to='seo_images/', verbose_name='Görsel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter kartları için kullanılır.', max_length=100, null=True, verbose_name='Twitter Kullanıcı Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'SEO ve Sosyal Medya',
                'verbose_name_plural': 'SEO ve Sosyal Medya',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Aboneler',
            },
        ),
        migrations.CreateModel(
            name='SubMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Görevler Başlığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.mission', verbose_name='Görevler')),
            ],
            options={
                'verbose_name_plural': 'Alt Görevler',
            },
        ),
    ]
