# Generated by Django 5.1.4 on 2025-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanner',
            name='subcsribe_description',
            field=models.TextField(blank=True, null=True, verbose_name='Abone Ol Banner Kısa Açıklaması'),
        ),
    ]
