# Generated by Django 5.1.4 on 2025-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pagebanner_subcsribe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanner',
            name='about_title',
            field=models.CharField(default=2, max_length=200, verbose_name='Hakkımızda Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='article_category_title',
            field=models.CharField(default=2, max_length=200, verbose_name='Makale Kategorisi Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='article_detail_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Makale Detayları Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='article_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Makale Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='contact_title',
            field=models.CharField(default=1, max_length=200, verbose_name='İletişim Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='galery_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Galeri Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='lesson_detail_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Ders Detayları Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='lesson_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Ders Banner Başlığı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='article_category_img',
            field=models.ImageField(upload_to='article_category_banner_img', verbose_name='Makale Kategorisi Banner Resmi'),
        ),
    ]
