# Generated by Django 5.1.4 on 2025-02-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pagebanner_about_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOModel',
        ),
    ]
