# Generated by Django 5.1.4 on 2025-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_seomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, help_text='Ana sayfa için boş bırakınız. Sayfa adı (örnek: Hakkımızda, Servis, Blog, Galeri, İletişim)', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(choices=[('author', 'Yazar'), ('description', 'Açıklama'), ('keywords', 'Anahtar Kelimeler'), ('robots', 'Robots'), ('viewport', 'Viewport'), ('og:title', 'Open Graph Başlığı'), ('og:description', 'Open Graph Açıklaması'), ('og:image', 'Open Graph Görseli'), ('twitter:title', 'Twitter Başlığı'), ('twitter:description', 'Twitter Açıklaması'), ('twitter:image', 'Twitter Görseli')], help_text='Meta adı veya özelliği', max_length=50)),
                ('content', models.TextField(help_text='Meta tag içeriği (content)')),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
