# Generated by Django 5.1.4 on 2025-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_metatag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalitem',
            name='main_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='En çok kullanılan telefon numarası'),
        ),
        migrations.AlterField(
            model_name='generalitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Site Adı'),
        ),
    ]
