# Generated by Django 5.1.4 on 2025-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_generalitem_main_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_reply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cevaplandı mı?'),
        ),
    ]
